### ISSUE TITLE
After install on laravel 5.4.* all test get error

### ISSUE THREAD

**Issue by abkrim** [socieboy/alerts#3]
This package work with Laravel 5.4?

it's possible upgrade?

```
PHPUnit 5.7.25 by Sebastian Bergmann and contributors.

.PHP Fatal error:  Cannot redeclare alert() (previously declared in /Users/abkrim/Sites/larabot/vendor/socieboy/alerts/src/helpers.php:3) in /Users/abkrim/Sites/larabot/vendor/socieboy/alerts/src/helpers.php on line 13
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php:895
Stack trace:
#0 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('Illuminate\\Cont...')
#3 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('Illuminate\\Cont...')
#4 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions in /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 895

Fatal error: Cannot redeclare alert() (previously declared in /Users/abkrim/Sites/larabot/vendor/socieboy/alerts/src/helpers.php:3) in /Users/abkrim/Sites/larabot/vendor/socieboy/alerts/src/helpers.php on line 13

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php:895
Stack trace:
#0 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('Illuminate\\Cont...')
#3 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('Illuminate\\Cont...')
#4 /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions in /Users/abkrim/Sites/larabot/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 895  
```

**Comment by socieboy** [comment]
I’m not longer maintaining the packages at this moment. You can submit a pull request if you want
